# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/markm/Downloads/RedPitaya-FPGA/prj/Examples/atan2_manual_v5/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0.xci
# IP: The module: 'system_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/markm/Downloads/RedPitaya-FPGA/prj/Examples/atan2_manual_v5/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/markm/Downloads/RedPitaya-FPGA/prj/Examples/atan2_manual_v5/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0.xci
# IP: The module: 'system_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/markm/Downloads/RedPitaya-FPGA/prj/Examples/atan2_manual_v5/tmp/freq/freq.srcs/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
